# Generated by Django 3.1 on 2020-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='rate',
            name='timestamp',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Unix Timestamp'),
        ),
    ]
